name: Aircon Control
version: "1.0.0"
slug: aircon-control
description: Web-based aircon control interface with zone control and timers
url: "https://github.com/your-repo/aircon-control"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
ingress: true
ingress_port: 8099
panel_icon: mdi:air-conditioner
panel_title: Aircon Control
panel_admin: false
homeassistant_api: false
host_network: false
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: Web interface port
options:
  aircon_server_ip: "192.168.8.196"
  aircon_server_port: 80
  aircon_server_password: ""
schema:
  aircon_server_ip: str
  aircon_server_port: int
  aircon_server_password: str
## The image field removed for local building from the included Dockerfile.
## When installing from Supervisor local add-ons, Supervisor will build the image from the Dockerfile.